
apiVersion: 1
datasources:
  - name: Postgres
    type: postgres
    access: proxy
    url: db:5432
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      database: talentverse
      sslmode: "disable"
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://otel-collector:8889
    isDefault: true
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3100
