
version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: talentverse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 20
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    command: ["start-dev", "--http-port=8081"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports: ["8081:8081"]
  loki:
    image: grafana/loki:2.9.8
    ports: ["3100:3100"]
    command: -config.file=/etc/loki/config.yaml
    volumes: [ "./observability/loki-prom/loki-config.yaml:/etc/loki/config.yaml:ro" ]
  grafana:
    image: grafana/grafana:11.0.0
    ports: ["3000:3000"]
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./observability/grafana:/var/lib/grafana/dashboards
volumes:
  pgdata:
