
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: talentverse-apps
spec:
  project: default
  source:
    repoURL: https://git.example/talentverse.git
    targetRevision: HEAD
    path: infra/k8s/helm/charts
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {{ prune: true, selfHeal: true }}
